name=input('what is your name: ')
fav_color=input('what is the favorate color: ')
birth_year=input('enter the birth year: ')
age=2020 -int(birth_year)
print(name +' likes '+fav_color)
print(age)
print(type(age))
print(type(name))
print(name[0])
print(name + ' is ' +str(age) +' years old')